### PR TITLE
Hourglass chart

### PR DESCRIPTION
**Pull request by geostag**
This adds an hourglass chart (#327)

However there are  three problems, which I did not manage by myself:

1. Could not find an overview over the available icons. Hourglass chart should have its own icon obviously
2. The default value for depth is "1" instead of "3" like with the other tree charts - did not find where to change
3. If depth is larger than 2, ancestor boxes are empty 

Any ideas how to fix?

### CODE REVIEW

**Comment by DavidMStraub** [comment]
Nice!

Regarding the icon: I just made this

```javascript
export const hourglassIcon = html`<svg height="24" width="24" viewBox="0 0 24 24">
<path fill="#000000" d="m3.501 3.5c-1.3807 0-2.5 1.1193-2.5 2.5 0 1.3807 1.1193 2.5 2.5 2.5 0.99358-5.12e-4 1.8916-0.58936 2.2891-1.5h1.2109v4h-1.2109c-0.39743-0.91064-1.2955-1.4995-2.2891-1.5-1.3807 0-2.5 1.1193-2.5 2.5s1.1193 2.5 2.5 2.5c0.99299-5.12e-4 1.8913-0.58834 2.2891-1.498h1.2109v4h-1.2109c-0.39743-0.91064-1.2955-1.4995-2.2891-1.5-1.3807 0-2.5 1.1193-2.5 2.5 0 1.3807 1.1193 2.5 2.5 2.5 0.99358-5.12e-4 1.8916-0.58936 2.2891-1.5h1.2109c1.1046 0 2-0.89543 2-2v-4.002h0.70898c0.39743 0.91064 1.2955 1.4995 2.2891 1.5 0.99359-5.12e-4 1.8916-0.58936 2.2891-1.5h0.71094v1c0 1.1046 0.89543 2 2 2h1.2109c0.39743 0.91064 1.2955 1.4995 2.2891 1.5 1.3807 0 2.5-1.1193 2.5-2.5 0-1.3807-1.1193-2.5-2.5-2.5-0.99359 5.13e-4 -1.8916 0.58936-2.2891 1.5h-1.2109v-4h1.2109c0.39743 0.91064 1.2955 1.4995 2.2891 1.5 1.3807 0 2.5-1.1193 2.5-2.5 0-1.3807-1.1193-2.5-2.5-2.5-0.99359 5.131e-4 -1.8916 0.58936-2.2891 1.5h-1.2109c-1.1046 0-2 0.89543-2 2v1h-0.71094c-0.39743-0.91064-1.2955-1.4995-2.2891-1.5-0.99359 5.12e-4 -1.8916 0.58936-2.2891 1.5h-0.70898v-4c0-1.1046-0.89543-2-2-2h-1.2109c-0.39743-0.91064-1.2955-1.4995-2.2891-1.5zm0 1.5c0.55228 0 1 0.44772 1 1s-0.44772 1-1 1c-0.55228 0-1-0.44772-1-1s0.44772-1 1-1zm16.998 3c0.55228 0 1 0.44772 1 1 0 0.55228-0.44772 1-1 1s-1-0.44772-1-1c0-0.55228 0.44772-1 1-1zm-16.998 3c0.55228 0 1 0.44772 1 1s-0.44772 1-1 1c-0.55228 0-1-0.44772-1-1s0.44772-1 1-1zm8.498 0c0.55228 0 1 0.44772 1 1s-0.44772 1-1 1-1-0.44772-1-1 0.44772-1 1-1zm8.5 3c0.55228 0 1 0.44772 1 1 0 0.55228-0.44772 1-1 1s-1-0.44772-1-1c0-0.55228 0.44772-1 1-1zm-19.27 1.0391h1.2109zm2.2715 1.9629c0.55228 0 1 0.44772 1 1 0 0.55228-0.44772 1-1 1-0.55228 0-1-0.44772-1-1 0-0.55228 0.44772-1 1-1z"/>
</svg>`
```

**Comment by DavidMStraub** [comment]
Regarding depth: `GrampsjsViewTreeChartBase` is where the API call to fetch the people is made, and it has two properties: `nAnc` and `nDesc`. At the moment, `GrampsjsTreeChart` only has a `depth` argument, but if we use this component also for hourglass, it's better to use `nAnc` and `nDesc` also for this component instead of `depth`.

**Comment by DavidMStraub** [comment]
... and then we can also remove `this._setAnc = false` in the constructor of `GrampsjsViewHourglassChart` and allow setting both depths independently.

Eventually, we can even think about getting rid of the ancestor and descendant charts...

**Comment by geostag** [comment]
thanks! Tried to implement this as suggested

**Comment by DavidMStraub** [comment]
Beautiful!

Three final suggestions:

- If we change the tab name to `Hourglass Graph` (rather than `Hourglass Tree`), we match the wording in Gramps Desktop and automatically have it translated to all languages
- Would you be OK with `nAnc=2` and `nDesc=1` as defaults? For my 18th/19th century ancestors with typically ~10 children per family, 2 descendant generation can get huge
- For consistency, `_resetLevels` should set to the same values as `constructor` (currently 2/2, 1/1).

**Comment by geostag** [comment]
added all three. Small hint: "Hourglass Graph" is translated to "Stundenglassdiagramm" in German which should be "Sanduhrdiagramm" IMO.

**Comment by DavidMStraub** [comment]
Oh, right 😬

I just checked that @Leonhaeuser already fixed it on Weblate, but we won't see it in Web until Gramps 5.2 is released unfortunately.

**Comment by DavidMStraub** [comment]
@geostag can you please rebase onto the current main branch so I can merge it? Thanks!

**Comment by geostag** [comment]
rebase done

**Pull request merged**
